<?php
$backup = file_get_contents("c:/xampp/htdocs/mtce/app/Controllers/RiwayatController_backup.php");

$serviceCode = "<?php\n\nnamespace App\Services;\n\nuse App\Models\TransaksiCheckModel;\nuse App\Models\TransaksiCheckDetailModel;\nuse CodeIgniter\I18n\Time;\n\nclass RiwayatService\n{\n";

// Function 1: validateLeaderAccess
$serviceCode .= "    public function validateLeaderAccess(?string \$lokasiName): ?string\n    {\n        if (session()->get('role') === 'leader') {\n            \$userLokasi = session()->get('lokasi');\n            if (\$userLokasi && \$userLokasi !== \$lokasiName) {\n                if (\$lokasiName === null) {\n                    return \$userLokasi;\n                } else {\n                    throw new \Exception('Akses ditolak.');\n                }\n            }\n        }\n        return \$lokasiName;\n    }\n\n";

// Function 2: getPdfAllData
$serviceCode .= "    public function getPdfAllData(?string \$lokasiName, array \$getParams): array\n    {\n        \$transaksiModel = new TransaksiCheckModel();\n        \$userLine = (session()->get('role') === 'leader') ? session()->get('line') : null;\n        \n        \$filters = [\n            'lokasi'      => \$lokasiName,\n            'id_mesin'    => (\$getParams['id_mesin'] ?? 'all') === 'all' ? null : (\$getParams['id_mesin'] ?? null),\n            'line'        => \$userLine ?: ((\$getParams['line'] ?? 'all') === 'all' ? null : (\$getParams['line'] ?? null)),\n            'jenis_check' => (\$getParams['jenis_check'] ?? 'all') === 'all' ? null : (\$getParams['jenis_check'] ?? null),\n            'kategori'    => (\$getParams['kategori'] ?? 'all') === 'all' ? null : (\$getParams['kategori'] ?? null),\n            'bulan'       => (\$getParams['bulan'] ?? 'all') === 'all' ? null : (\$getParams['bulan'] ?? null),\n            'status'      => (\$getParams['status'] ?? 'all') === 'all' ? null : (\$getParams['status'] ?? null),\n            'pic'         => (\$getParams['pic'] ?? 'all') === 'all' ? null : (\$getParams['pic'] ?? null),\n            'sort_by'     => \$getParams['sort_by'] ?? 'id_transaksi',\n            'order'       => \$getParams['order'] ?? 'desc',\n        ];\n\n        \$riwayat = \$transaksiModel->getRiwayatFiltered(\$filters);\n        \n        \$detailModel = new TransaksiCheckDetailModel();\n        \$allReports = [];\n        foreach (\$riwayat as \$row) {\n            \$header = \$transaksiModel->getDetailTransaksi(\$row['id_transaksi']);\n            if (\$header) {\n                \$details = \$detailModel->getDetailByTransaksi(\$row['id_transaksi']);\n                \$details = \$detailModel->calculateRowspans(\$details, \$header['jenis_check']);\n                \$allReports[] = [\n                    'header' => \$header,\n                    'details' => \$details\n                ];\n            }\n        }\n        \n        \$jenisLabel = \$filters['jenis_check'] === 'Preventive' ? 'Checklist Report' : (\$filters['jenis_check'] === 'Overhaul' ? 'Inspection Report' : 'Pengecekan');\n\n        return [\n            'title'      => \"Riwayat {\$jenisLabel} - {\$lokasiName}\",\n            'allReports' => \$allReports,\n            'filters'    => \$filters,\n            'lokasiName' => \$lokasiName,\n            'jenisLabel' => \$jenisLabel\n        ];\n    }\n\n";

// Function 3: getDetailData
$serviceCode .= "    public function getDetailData(int \$id, ?string \$roleSession): ?array\n    {\n        \$transaksiModel = new TransaksiCheckModel();\n        \$header         = \$transaksiModel->getDetailTransaksi(\$id);\n\n        if (! \$header) {\n            return null;\n        }\n\n        \$approvalStatus = \$header['status'] ?? 'Pending';\n        \n        if (\$roleSession === 'sheadprd' && \$approvalStatus === 'Pending') {\n            throw new \Exception('Dokumen ini belum siap (Masih menunggu Leader).');\n        }\n        if (\$roleSession === 'sheadmtc' && in_array(\$approvalStatus, ['Pending', 'Approved L1'], true)) {\n            throw new \Exception('Dokumen ini belum siap (Masih menunggu SHead Produksi).');\n        }\n\n        \$detailModel = new TransaksiCheckDetailModel();\n        \$details     = \$detailModel->getDetailByTransaksi(\$id);\n        \$details     = \$detailModel->calculateRowspans(\$details, \$header['jenis_check']);\n\n        \$durasiDetik = null;\n        if (! empty(\$header['waktu_mulai']) && ! empty(\$header['waktu_selesai'])) {\n            \$durasiDetik = strtotime(\$header['waktu_selesai']) - strtotime(\$header['waktu_mulai']);\n        }\n\n        \$leaderPicModel = new \App\Models\PicModel();\n        if (\$roleSession === 'leader') {\n            \$userLine = session()->get('line');\n            if (\$userLine === 'Line 1') {\n                \$leaderPicModel->where('role_pic', 'leader1');\n            } elseif (\$userLine === 'Line 2') {\n                \$leaderPicModel->where('role_pic', 'leader2');\n            } elseif (\$userLine === 'Line 3') {\n                \$leaderPicModel->where('role_pic', 'leader3');\n            } elseif (\$userLine === 'CG') {\n                \$leaderPicModel->where('role_pic', 'leadercg');\n            } elseif (\$userLine === 'Second') {\n                \$leaderPicModel->where('role_pic', 'leadersc');\n            } else {\n                \$leaderPicModel->like('role_pic', 'leader', 'both');\n            }\n        } else {\n            \$leaderPicModel->like('role_pic', 'leader', 'both');\n        }\n        \$leaderPicList = \$leaderPicModel->findAll();\n\n        return [\n            'header'      => \$header,\n            'details'     => \$details,\n            'durasiDetik' => \$durasiDetik,\n            'staffPicList' => (new \App\Models\PicModel())->where('role_pic', 'Staff')->findAll(),\n            'leaderPicList'=> \$leaderPicList,\n        ];\n    }\n\n";

// Function 4: getRedirectDetailUrl
$serviceCode .= "    public function getRedirectDetailUrl(array \$getParams): ?string\n    {\n        \$idMesin  = \$getParams['id_mesin'] ?? null;\n        \$kategori = \$getParams['kategori'] ?? null;\n        \$bulan    = \$getParams['bulan'] ?? null;\n        \$line     = \$getParams['line'] ?? null;\n        \$lokasi   = \$getParams['lokasi'] ?? null;\n\n        \$db = \Config\Database::connect();\n        \$tx = \$db->table('transaksi_check')\n                 ->select('id_transaksi')\n                 ->where('id_mesin', \$idMesin)\n                 ->where('kategori', \$kategori)\n                 ->like('waktu_mulai', \$bulan, 'after')\n                 ->orderBy('id_transaksi', 'DESC')\n                 ->get()\n                 ->getRowArray();\n\n        if (\$tx) {\n            \$qsArray = [\n                'from'     => 'kontrol',\n                'lokasi'   => \$lokasi,\n                'line'     => \$line,\n                'kategori' => \$kategori,\n                'bulan'    => \$bulan,\n            ];\n            \$qsSummary = \$getParams['qs_summary'] ?? null;\n            if (\$qsSummary) {\n                \$qsArray['qs_summary'] = \$qsSummary;\n            }\n            \$qs = http_build_query(\$qsArray);\n            return '/riwayat/' . \$tx['id_transaksi'] . '?' . \$qs;\n        }\n        \n        return null;\n    }\n\n";

// Function 5: getPdfData
$serviceCode .= "    public function getPdfData(int \$id): ?array\n    {\n        \$transaksiModel = new TransaksiCheckModel();\n        \$header         = \$transaksiModel->getDetailTransaksi(\$id);\n\n        if (! \$header) {\n            return null;\n        }\n\n        \$detailModel = new TransaksiCheckDetailModel();\n        \$details     = \$detailModel->getDetailByTransaksi(\$id);\n        \$details     = \$detailModel->calculateRowspans(\$details, \$header['jenis_check']);\n\n        \$durasiDetik = null;\n        if (! empty(\$header['waktu_mulai']) && ! empty(\$header['waktu_selesai'])) {\n            \$durasiDetik = strtotime(\$header['waktu_selesai']) - strtotime(\$header['waktu_mulai']);\n        }\n\n        return [\n            'header'      => \$header,\n            'details'     => \$details,\n            'durasiDetik' => \$durasiDetik,\n        ];\n    }\n\n";

// Function 6: getEditData
$serviceCode .= "    public function getEditData(int \$id): ?array\n    {\n        \$transaksiModel = new TransaksiCheckModel();\n        \$header = \$transaksiModel->getDetailTransaksi(\$id);\n        if (!\$header) {\n            return null;\n        }\n\n        \$detailModel = new \App\Models\TransaksiCheckDetailModel();\n        \$details = \$detailModel->where('id_transaksi', \$id)->findAll();\n\n        \$detailsMap = [];\n        foreach (\$details as \$d) {\n            \$detailsMap[\$d['id_parameter']] = \$d;\n        }\n\n        \$mesinModel = new \App\Models\MesinModel();\n        \$parameterModel = new \App\Models\ParameterCheckModel();\n        \n        \$lokasiSlug = strtolower(str_replace(' ', '', \$header['lokasi_check']));\n        \$jenisSlug = strtolower(str_replace(' ', '-', \$header['jenis_check']));\n        \n        \$categoryMap = [\n            'penerangan' => 'Penerangan',\n            'panel' => 'Panel',\n            'inverter' => 'Inverter',\n            'motor' => 'Motor',\n            'sensor' => 'Sensor',\n            'pintu' => 'Pintu',\n            'safety' => 'Safety',\n            'fan' => 'Fan / Blower',\n            'lain' => 'Lain-Lain'\n        ];\n        \$categorySlug = array_search(\$header['kategori'], \$categoryMap, true) ?: 'penerangan';\n        \n        \$waktuMulai = new \CodeIgniter\I18n\Time(\$header['waktu_mulai']);\n\n        return [\n            'title'             => \"Edit Pengecekan {\$header['jenis_check']} - {\$header['kategori']}\",\n            'lokasiSlug'        => \$lokasiSlug,\n            'lokasiName'        => \$header['lokasi_check'],\n            'jenisSlug'         => \$jenisSlug,\n            'jenisName'         => \$header['jenis_check'],\n            'categorySlug'      => \$categorySlug,\n            'categoryName'      => \$header['kategori'],\n            'daftarMesin'       => \$mesinModel->getByLokasi(\$header['lokasi_check']),\n            'rows'              => \$parameterModel->getFormRows(\$header['lokasi_check'], \$header['jenis_check'], \$header['kategori']),\n            'masterPic'         => array_filter((new \App\Models\PicModel())->findAll(), function(\$p) {\n                return strpos(strtolower(str_replace(' ', '', \$p['role_pic'] ?? '')), 'leader') === false;\n            }),\n            'staffPic'          => (new \App\Models\PicModel())->where('role_pic', 'Staff')->findAll(),\n            'namaPic'           => \$header['nama_pic'],\n            'namaStaff'         => \$header['nama_staff'],\n            'waktuMulai'        => \$header['waktu_mulai'],\n            'waktuMulaiDisplay' => \$waktuMulai->toLocalizedString('dd MMMM yyyy, HH:mm:ss'),\n            'idMesin'           => \$header['id_mesin'],\n            'isEdit'            => true,\n            'idTransaksi'       => \$id,\n            'detailsMap'        => \$detailsMap,\n        ];\n    }\n\n";

// Function 7: deleteTransaksi
$serviceCode .= "    public function deleteTransaksi(int \$id): bool\n    {\n        \$transaksiModel = new TransaksiCheckModel();\n        \$header = \$transaksiModel->find(\$id);\n        if (!\$header) {\n            return false;\n        }\n\n        \$detailModel = new \App\Models\TransaksiCheckDetailModel();\n        \$details = \$detailModel->where('id_transaksi', \$id)->findAll();\n\n        \$uploadPath = FCPATH . 'uploads/abnormal/';\n        foreach (\$details as \$d) {\n            if (\$d['foto_abnormal'] && file_exists(\$uploadPath . \$d['foto_abnormal'])) {\n                @unlink(\$uploadPath . \$d['foto_abnormal']);\n            }\n            if (\$d['foto_abnormal_2'] && file_exists(\$uploadPath . \$d['foto_abnormal_2'])) {\n                @unlink(\$uploadPath . \$d['foto_abnormal_2']);\n            }\n        }\n\n        \$transaksiModel->delete(\$id);\n        return true;\n    }\n\n";

$startUpdate = strpos($backup, "public function update(int \$id)");
$startDelete = strpos($backup, "public function delete(int \$id)");
$startApprove = strpos($backup, "public function approve(\$idTransaksi)");

$updateMethod = substr($backup, $startUpdate, $startDelete - $startUpdate);
$approveMethod = substr($backup, $startApprove, strlen($backup) - $startApprove - 4);

$updateService = str_replace('public function update(int $id)', 'public function updateTransaksi(int $id, $request, $validation)', $updateMethod);
$updateService = str_replace('$this->request', '$request', $updateService);
$updateService = str_replace('$this->validate($rules)', '$validation->setRules($rules); if (!$validation->withRequest($request)->run()) return ["status" => false, "errors" => $validation->getErrors()]; return true', $updateService);
$updateService = preg_replace("/return redirect\(\)->back\(\)->withInput\(\)->with\('errors', \\\\Config\\\\Services::validation\(\)->getErrors\(\)\);/", "", $updateService);
$updateService = preg_replace("/return redirect\(\)->back\(\)->with\('error', (.*?)\);/", 'return ["status" => false, "message" => $1];', $updateService);
$updateService = preg_replace("/return redirect\(\)->to\(.*?\)->with\('success', (.*?)\);/", 'return ["status" => true, "message" => $1];', $updateService);
$updateService = preg_replace("/return redirect\(\)->back\(\)->withInput\(\)->with\('error', (.*?)\);/", 'return ["status" => false, "message" => $1];', $updateService);

$approveService = str_replace('public function approve($idTransaksi)', 'public function approveTransaksi($idTransaksi, $request)', $approveMethod);
$approveService = str_replace('$this->request', '$request', $approveService);
$approveService = preg_replace("/return redirect\(\)->back\(\)->with\('error', (.*?)\);/", 'return ["status" => false, "message" => $1];', $approveService);
$approveService = preg_replace("/return redirect\(\)->back\(\)->with\('success', (.*?)\);/", 'return ["status" => true, "message" => $1];', $approveService);

$serviceCode .= $updateService . "\n" . $approveService . "\n}\n";

file_put_contents("c:/xampp/htdocs/mtce/app/Services/RiwayatService.php", $serviceCode);
echo "RiwayatService successfully written completely fresh.\n";
