<?php
$controllerCode = file_get_contents("c:/xampp/htdocs/mtce/app/Controllers/RiwayatController.php");

$controllerCode = preg_replace('/public function downloadPdfAll\(string \$lokasiSlug\).*?public function detail\(int \$id\)/s', "public function downloadPdfAll(string \$lokasiSlug)\n    {\n        \$lokasiName = \$this->resolveLokasi(\$lokasiSlug);\n        \$riwayatService = new \App\Services\RiwayatService();\n        try {\n            \$lokasiName = \$riwayatService->validateLeaderAccess(\$lokasiName);\n        } catch (\Exception \$e) {\n            return redirect()->to('/dashboard')->with('error', \$e->getMessage());\n        }\n        \$data = \$riwayatService->getPdfAllData(\$lokasiName, \$this->request->getGet());\n        \$html = view('riwayat/pdf_all_details', \$data);\n        \$options = new \\Dompdf\\Options();\n        \$options->set('isHtml5ParserEnabled', true);\n        \$options->set('isRemoteEnabled', true);\n        \$dompdf = new \\Dompdf\\Dompdf(\$options);\n        \$dompdf->loadHtml(\$html);\n        \$dompdf->setPaper('A4', 'portrait');\n        \$dompdf->render();\n        \$filename = \"Summary_Riwayat_\" . str_replace(' ', '_', \$data['jenisLabel']) . \"_\" . date('Ymd_His') . \".pdf\";\n        \$dompdf->stream(\$filename, [\"Attachment\" => true]);\n    }\n\n    public function detail(int \$id)", $controllerCode);

$controllerCode = preg_replace('/public function detail\(int \$id\).*?public function redirectDetail\(\)/s', "public function detail(int \$id)\n    {\n        \$riwayatService = new \App\Services\RiwayatService();\n        try {\n            \$data = \$riwayatService->getDetailData(\$id, session()->get('role'));\n        } catch (\Exception \$e) {\n            return redirect()->to('/dashboard')->with('error', \$e->getMessage());\n        }\n        if (! \$data) {\n            return redirect()->to('/riwayat')->with('error', 'Transaksi tidak ditemukan.');\n        }\n        \$data['title'] = 'Detail Pengecekan';\n        \$data['from'] = \$this->request->getGet('from');\n        \$data['cb_lokasi'] = \$this->request->getGet('lokasi');\n        \$data['cb_line'] = \$this->request->getGet('line');\n        \$data['cb_kategori'] = \$this->request->getGet('kategori');\n        \$data['cb_bulan'] = \$this->request->getGet('bulan');\n        \$data['staffPic'] = \$data['staffPicList'];\n        return view('riwayat/detail', \$data);\n    }\n\n    public function redirectDetail()", $controllerCode);

$controllerCode = preg_replace('/public function redirectDetail\(\).*?public function downloadPdf\(int \$id\)/s', "public function redirectDetail()\n    {\n        \$riwayatService = new \App\Services\RiwayatService();\n        \$url = \$riwayatService->getRedirectDetailUrl(\$this->request->getGet());\n        if (\$url) {\n            return redirect()->to(\$url);\n        } else {\n            return redirect()->to('/riwayat/lokasi/' . rawurlencode(\$this->request->getGet('lokasi')) . '?line=' . rawurlencode(\$this->request->getGet('line')) . '&kategori=' . rawurlencode(\$this->request->getGet('kategori')) . '&bulan=' . rawurlencode(\$this->request->getGet('bulan')) . '&id_mesin=' . rawurlencode(\$this->request->getGet('id_mesin')))->with('error', 'Belum ada laporan untuk mesin ini di bulan yang dipilih.');\n        }\n    }\n\n    public function downloadPdf(int \$id)", $controllerCode);

$controllerCode = preg_replace('/public function downloadPdf\(int \$id\).*?public function edit\(int \$id\)/s', "public function downloadPdf(int \$id)\n    {\n        \$riwayatService = new \App\Services\RiwayatService();\n        \$data = \$riwayatService->getPdfData(\$id);\n        if (! \$data) {\n            return redirect()->to('/riwayat')->with('error', 'Transaksi tidak ditemukan.');\n        }\n        \$data['title'] = 'Detail Pengecekan';\n        \$html = view('riwayat/detail_pdf', \$data);\n        \$options = new \\Dompdf\\Options();\n        \$options->set('isHtml5ParserEnabled', true);\n        \$options->set('isRemoteEnabled', true);\n        \$options->set('defaultFont', 'DejaVu Sans');\n        \$dompdf = new \\Dompdf\\Dompdf(\$options);\n        \$dompdf->loadHtml(\$html);\n        \$dompdf->setPaper('A4', 'portrait');\n        \$dompdf->render();\n        \$filename = 'Laporan_' . (\$data['header']['jenis_check'] === 'Preventive' ? 'Checklist' : 'Inspection') . '_' . \$data['header']['no_mesin'] . '_' . date('Ymd', strtotime(\$data['header']['waktu_mulai'])) . '.pdf';\n        \$dompdf->stream(\$filename, [\"Attachment\" => true]);\n        exit();\n    }\n\n    public function edit(int \$id)", $controllerCode);

$controllerCode = preg_replace('/public function edit\(int \$id\).*?\}\s*$/s', "public function edit(int \$id)\n    {\n        if (session()->get('role') !== 'admin') {\n            return redirect()->back()->with('error', 'Akses ditolak.');\n        }\n        \$riwayatService = new \App\Services\RiwayatService();\n        \$data = \$riwayatService->getEditData(\$id);\n        if (!\$data) {\n            return redirect()->back()->with('error', 'Transaksi tidak ditemukan.');\n        }\n        return view('riwayat/edit', \$data);\n    }\n\n    public function update(int \$id)\n    {\n        if (session()->get('role') !== 'admin') {\n            return redirect()->back()->with('error', 'Akses ditolak.');\n        }\n        \$riwayatService = new \App\Services\RiwayatService();\n        \$result = \$riwayatService->updateTransaksi(\$id, \$this->request, \Config\Services::validation());\n        if (isset(\$result['errors'])) {\n            return redirect()->back()->withInput()->with('errors', \$result['errors']);\n        }\n        if (!\$result['status']) {\n            return redirect()->back()->with('error', \$result['message']);\n        }\n        return redirect()->back()->with('success', \$result['message'] ?? 'Riwayat berhasil diperbarui.');\n    }\n\n    public function delete(int \$id)\n    {\n        if (session()->get('role') !== 'admin') {\n            return redirect()->back()->with('error', 'Akses ditolak.');\n        }\n        \$riwayatService = new \App\Services\RiwayatService();\n        if (\$riwayatService->deleteTransaksi(\$id)) {\n            return redirect()->back()->with('success', 'Transaksi berhasil dihapus.');\n        }\n        return redirect()->back()->with('error', 'Transaksi tidak ditemukan.');\n    }\n\n    public function approve(\$idTransaksi)\n    {\n        \$riwayatService = new \App\Services\RiwayatService();\n        \$result = \$riwayatService->approveTransaksi(\$idTransaksi, \$this->request);\n        if (!\$result['status']) {\n            return redirect()->back()->with('error', \$result['message']);\n        }\n        return redirect()->back()->with('success', \$result['message']);\n    }\n}\n", $controllerCode);

file_put_contents("c:/xampp/htdocs/mtce/app/Controllers/RiwayatController.php", $controllerCode);
echo "RiwayatController shrunk successfully.\n";
